### PR TITLE
fix(delete-env): proper warning on 404

### PR DESCRIPTION
**Pull request by mtfurlan**
When we get a 404 deleting an environment there should be a better
warning than "unexpected error encountered: HttpError: Not Found"
Document in the readme that the user for the PAT must have admin on the
repo, not just write or manage.

### CODE REVIEW

**Comment by mmkoles** [comment]
Thanks for the PR.
It helped me to resolve why my env deletions are failing 👍

**Review by mmkoles — APPROVED** [review]
lgtm

**Comment by sguha00** [comment]
@mtfurlan I've been strugging with getting delete-env to work. Does this work with fine-grained personal access tokens or just the classic tokens?

**Comment by mtfurlan** [comment]
Yeah, this repo works with PATs, but as I have in the readme change, the PAT needs repo scope permissions, and the owner of the PAT needs to be admin on the repo.

**Review by bobheadxi — APPROVED** [review]

**Pull request merged**
