### PR TITLE
[BUGFIX] Don't deactivate already inactive deployments

### PR DESCRIPTION
**Pull request by paullarsen-unlikely**
#92 Mentions errors regarding deployments having the max number of statuses already set.

This PR avoids this from happening, by only setting the status if the status isn't already "inactive".

### CODE REVIEW

**Comment by bobheadxi** [comment]
Thank you for the contribution! I'll get this merged and released this week, but need to figure out why GitHub actions didn't run on this branch 🤔

**Comment by paullarsen-unlikely** [comment]
> Thank you for the contribution! I'll get this merged and released this week, but need to figure out why GitHub actions didn't run on this branch 🤔

@bobheadxi i believe this is due to the missing `pull_request` action in the `pipeline.yaml`. It's currently set to "push", which only works if its a push to a branch on THIS repo; since my repo is a fork, it doesnt count. 

Hopefully fixed by #109?

**Review by bobheadxi — APPROVED** [review]
Thank you :)

**Comment by bobheadxi** [comment]
@paullarsen-unlikely There appear to be some formatting issues, do you mind fixing them? Thank you!

**Review by vhatsura — COMMENTED** [review]
@paullarsen-unlikely , looks good. Can you run `npm run prettier` to fix formatting issues?

**Comment by paullarsen-unlikely** [comment]
@bobheadxi Formatting has been fixed - sorry for the delay!

**Review by vhatsura — APPROVED** [review]

**Review by bobheadxi — APPROVED** [review]
Let's go, thank you :)

**Comment by bobheadxi** [comment]
Looks like integration tests don't work on forked PRs - might be something to look into @vhatsura !

**Comment by bobheadxi** [comment]
Integration tests look healthy in `main`: https://github.com/bobheadxi/deployments/runs/6996779510?check_suite_focus=true

**Comment by bobheadxi** [comment]
I've cut a release for this change: https://github.com/bobheadxi/deployments/releases/tag/v1.3.0

**Pull request merged**
