### PR TITLE
Bump actions/core

### LINKED ISSUE #123: Warning: The `set-output` command is deprecated and will be disabled soon
Recently this action started to indicate the following warning message.

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

I found the solution in this discussion
https://github.com/orgs/community/discussions/35994

Basically you should output to $GITHUB_OUTPUT and stop using set-output command.
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

Example:
```YAML
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
```

### PR DESCRIPTION
**Pull request by johncarter-phntm**
To fix #123

### CODE REVIEW

**Review by bobheadxi — APPROVED** [review]

**Comment by johncarter-phntm** [comment]
Tests are failing with "unexpected error encountered: HttpError: Resource not accessible by integration", I'm assuming that's due to a permissions issue unrelated to my change.

**Comment by vhatsura** [comment]
@johncarter-phntm, this is due to CI running against your fork, and in case it's impossible to update deployment of the origin. I've tried to find a way how to run tests against forks, but failed in my research

**Comment by dev31000** [comment]
Is there any update on this PR?

**Comment by johncarter-phntm** [comment]
Hi @bobheadxi can you merge this?

**Pull request merged**
