### PR TITLE
add action parameters

### PR DESCRIPTION
**Pull request by louy**
Add missing inputs to avoid warnings

### CODE REVIEW

**Comment by gersmann** [comment]
@bobheadxi could you merge this? This looks pretty useful.

**Comment by lintaonz** [comment]
I agree. It's very annoying that Github keep complaining 
`Unexpected input(s) 'status', 'deployment_id', valid inputs are ['token', 'step', 'auto_inactive', 'logs', 'desc', 'ref']`

**Comment by pperzyna** [comment]
+1

**Comment by CalebAlbers** [comment]
@bobheadxi any chance you could take a look at this?

**Comment by zenion** [comment]
+1 👍

**Review by bobheadxi — APPROVED** [review]
LGTM - thank you!

**Pull request merged**
